<br>
<img align="center" src="imagenes/logo.png"  width="200" height="141">
<font size=36><center> Machine Learning con Python </center> </font>
<br>

<h1 align='center'> Modulo III: Procesamiento y visualización de datos </h1>
<h2 align='center'>  Introducción a librería Numpy </h2>  

---

Numpy es una librería para realizar cálculo numérico en python. Nos permite crear y modificar matrices, y hacer operaciones sobre ellas con facilidad.

Para comenzar a usar numpy, debemos importar la librería. En este caso la vamos a importar, y darle un alias al mismo tiempo, np, para que el código sea más legible.

In [1]:
import numpy as np # Usualmente se usa np como alias

## Creación de arreglos

### Arreglos unidimensionales

In [3]:
# Creamos un arreglo de dígitos del 0 al 8
arreglo1 = np.arange(8)
arreglo1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
# Creando un arreglo a partir de una lista
lista=[12,24,4,3,55,0]

In [5]:
vector = np.array(lista)
vector

array([12, 24,  4,  3, 55,  0])

### ¿Cuál es la diferencia entre vector y lista? 
Que vector, al ser un arreglo de numpy, nos permite hacer varias operaciones matemáticas de forma muy simple.

#### Ejemplos

In [6]:
# Sumar un escalar
print(vector +1)

[13 25  5  4 56  1]


In [7]:
# Multiplicar por un escalar
print(vector*5)

[ 60 120  20  15 275   0]


In [8]:
# Sumar elementos de una vector
print(np.sum(vector))

98


In [9]:
# Promedio de los elementos
print(np.mean(vector))

16.333333333333332


In [10]:
# Suma de dos vectores
vector2 = np.array([0,1,2,3,4,5])
print(vector+vector2)

[12 25  6  6 59  5]


### índices de vectores

In [11]:
# Segundo elemento del vector (indice 1)
print(vector[1])

24


In [12]:
# Elementos de 1 hasta 3 (el extremo derecho es abierto)
print(vector[1:4])

[24  4  3]


In [13]:
# Todos los elemenetos a partir de un indice 
print(vector[1:])

[24  4  3 55  0]


In [14]:
# Todos los elementos cuyo índice es menor a 4
print(vector[:4])

[12 24  4  3]


In [15]:
# Copia del vector original
print(vector[:])

[12 24  4  3 55  0]


### Vector nulo

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### Vector de unos

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

## Matrices

Los vectores son arreglos de una sola dimensión. Las matrices son arreglos de dos dimensiones; generalmente a la primera dimensión se la llama la de las **filas**, mientras que a la otra se la llama la de las **columnas**.

Por ende, para crearlas con np.array, necesitamos no una lista de valores, sino una lista de valores por cada fila, o sea, una lista de listas.

Del mismo modo, para crearlas con np.zeros o np.ones, vamos a necesitar una tupla con dos elementos, uno por cada dimensión.

#### Ejemplos

In [17]:
lista_de_listas=[ [1  ,-4], [12 , 3], [7.2, 5]]
matriz = np.array(lista_de_listas)
print(matriz)

[[ 1.  -4. ]
 [12.   3. ]
 [ 7.2  5. ]]


In [18]:
# Dimensión de la matriz
matriz.shape

(3, 2)

In [19]:
#Matriz nula de orden 3x2
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
# Matriz de unos de orden 3x2
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Elementos de una matriz

In [22]:
# Elemento 1,1 de la matriz o 0,1 a partir de los indices
matriz[0,1]

-4.0

In [23]:
matriz

array([[ 1. , -4. ],
       [12. ,  3. ],
       [ 7.2,  5. ]])

In [25]:
# Elemento 2,1
matriz[2,0]

7.2

In [26]:
#Fila 1
matriz[1,:]

array([12.,  3.])

In [41]:
#columna 0
matriz[:,0]

array([ 1. , 12. ,  7.2])

In [27]:
# Submatriz
matriz[0:2,1]

array([-4.,  3.])

### Modificando los elementos de la matriz

In [28]:
matriz[0,1] = 2

In [29]:
matriz[0,1]

2.0

### Operaciones Básicas

La mayoría de las operaciones que se pueden aplicar en los ndarray se encuentran en el espacio de nombres de np, y las cuales son bastante directas:

In [51]:
# Vamos a generar varios ndarrays
a = np.array([[1, 2, 3], [4, 5, 6]])

#Función seno
b = np.sin(a)

In [52]:
print(b)

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [56]:
# Generando datos aleatorios
c = np.random.rand(2,3)

In [55]:
print(c)

[[0.47245444 0.47745604 0.62816158]
 [0.09409092 0.32684518 0.70163471]]


In [59]:
# Multiplicación elemento a elemento
a*c

array([[0.14604818, 0.12450182, 1.27499986],
       [3.58075612, 0.65640365, 2.87933163]])

In [60]:
d=np.random.rand(3,2)

In [62]:
# Producto usual de matrices
np.dot(a,d)

array([[2.20634004, 1.98674602],
       [5.14185496, 5.56421661]])

In [64]:
# Suma de elementosde cada columna
matriz.sum(axis=0)

array([20.2, 10. ])

In [65]:
# Suma de elementos de cada filas
matriz.sum(axis=1)

array([ 3. , 15. , 12.2])

In [66]:
matriz.sum()

30.2

In [68]:
np.power(matriz,2)

array([[  1.  ,   4.  ],
       [144.  ,   9.  ],
       [ 51.84,  25.  ]])

In [2]:
A=np.random.randn(3,3)

In [3]:
A


array([[-0.72681564, -0.24493215,  1.19716749],
       [ 0.38909054, -1.9526934 ,  0.92406685],
       [ 0.62024148,  0.67580338, -1.93953966]])

In [5]:
A.shape

(3, 3)

In [9]:
A.diagonal()

array([-0.72681564, -1.9526934 , -1.93953966])